version: '3.7'
services:
  mongo:
    image: 'mongo'

  Back:
    image: foraneo/webapi:latest
    restart: always
    ports:
      - 5000:80

    depends_on:
      - mongo
  Front:
    image: foraneo/front_produccion:latest
    restart: always
    ports: 
      - '8080:8080'
  
